name: Build Debian Package
description: |
  Builds the debian package represented by this repo at the ref pointed by the debain-ref argument.

on:
  workflow_dispatch:
    inputs:

      debian-ref:
        description: The debian ref to build. For example branch "debian/qcom-next" or tag "debian/1.0.0-1"
        type: string
        required: true
        default: debian/qcom-next

      suite:
        description: The distribution codename or Debian suite to build for. Ex noble, questing, resolute, trixie, sid, unstable
        type: choice
        default: unstable
        options:
          - noble
          - questing
          - resolute
          - unstable
          - forky
          - trixie
          - bookworm
          - sid

permissions:
  contents: read
  packages: read

jobs:
  build:
    uses: qualcomm-linux/qcom-build-utils/.github/workflows/qcom-build-pkg-reusable-workflow.yml@main
    with:
      qcom-build-utils-ref: main
      debian-ref: ${{ inputs.debian-ref }}
      suite: ${{ inputs.suite }}
      debusine-parent-workspace: ${{ vars.DEBUSINE_PARENT_WORKSPACE || 'ci' }}
